/* eslint-disable max-len */
module.exports = [
  {
    title: "Informatika Media Pratama",
    from: "2023",
    to: "now",
    descriptionHtml: "Fullstack Developer",
    techs: ["Laravel", "MySQL", "React"],
  },
  {
    title: "DOT Indonesia",
    from: "2022",
    to: "now",
    descriptionHtml: "Backend Developer",
    techs: ["Laravel", "MySQL", "React"],
  },
  {
    title: "Antardata Cakrawala Teknologi",
    from: "2020",
    to: "2023",
    descriptionHtml: "Fullstack developer",
    techs: [
      "Laravel",
      "CodeIgniter",
      "Yii",
      "ReactJS",
      "ReactNative",
      "SQL",
      "NoSQL",
      "Microservice",
      "ExpressJS",
    ],
  },
  {
    title: "Epsilon Multisinergi",
    from: "2020",
    to: "2022",
    descriptionHtml: "Fullstack developer",
    techs: ["Laravel", "CodeIgniter", "ReactJS", "SQL", "NoSQL", "AdonisJS"],
  },
  {
    title: "Xplora Gamma Jaya",
    from: "2018",
    to: "2022",
    descriptionHtml: "Fullstack developer",
    techs: [
      "Laravel",
      "ReactJS",
      "ExpresJS",
      "ReactNative",
      "SQL",
      "NoSQL",
      "Microservice",
    ],
  },
  {
    title: "Aslamindo Eltama Raya",
    from: "2016",
    to: "2018",
    descriptionHtml: "Fullstack developer",
    techs: ["Laravel", "Java", ".Net", "SQL Server"],
  },
  {
    title: "Auto 2000 Jember",
    from: "2013",
    to: "now",
    descriptionHtml: "Freelance fullstack developer",
    techs: ["Laravel", "MySQL", "ReactJS"],
  },
];
